<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_custom-code-settings',
		'title' => 'Custom Code Settings',
		'fields' => array (
			array (
				'key' => 'field_539dc157e6560',
				'label' => 'Custom CSS',
				'name' => 'nill_custom_css',
				'type' => 'textarea',
				'instructions' => 'Add your custom code',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539dc178e6561',
				'label' => 'Custom Google Code',
				'name' => 'nill_googlecode',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-custom-code',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-general-settings',
		'title' => 'Nill General Settings',
		'fields' => array (
			array (
				'key' => 'field_538e915ad702b',
				'label' => 'Theme',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538e9165d702c',
				'label' => 'Logo Upload',
				'name' => 'nill_logoupload',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53917a3d7d690',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538df4cbf519c',
				'label' => 'Sidebar Styles',
				'name' => 'nill_sidebarstyle',
				'type' => 'select',
				'instructions' => 'Select Sidebar Opener Effects',
				'choices' => array (
					1 => 'Slide In Top',
					2 => 'Reveal',
					3 => 'Push',
					4 => 'Slide Along',
					5 => 'Reverse Slide Out',
					6 => 'Rotate Pusher',
					7 => '3D Rotate In',
					8 => '3D Rotate Out',
					9 => 'Scale Down Pusher',
					10 => 'Scale Up',
					11 => 'Scale And Rotate Pusher',
					12 => 'Open Door',
					13 => 'Fail Down',
					14 => 'Delayed 3D Rotate',
				),
				'default_value' => 1,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5390592a7c25e',
				'label' => 'Modal Box Styles',
				'name' => 'nill_modalbox',
				'type' => 'select',
				'instructions' => 'Select Modal Box Opener Effects',
				'choices' => array (
					1 => 'Fade in Scale',
					2 => 'Slide in Right',
					3 => 'Slide in Bottom',
					4 => 'Newspaper',
					5 => 'Fail',
					6 => 'Side Fail',
					7 => 'Sticky Up',
					8 => '3D Flip Horizantal',
					9 => '3D Flip Vertical',
					10 => '3D Sign',
					11 => 'Super Scaled',
					12 => '3D Split',
					13 => '3D Rotate Bottom',
					14 => '3D Rotate in Left',
					15 => 'Blur',
					16 => 'Let Me in',
					17 => 'Make Way',
					18 => 'Slip From Top',
				),
				'default_value' => 1,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53917a8b09b8d',
				'label' => 'Picture Slider Styles',
				'name' => 'nill_picturestyles',
				'type' => 'select',
				'instructions' => 'Select Picture Slider Effects',
				'choices' => array (
					'fxCorner' => 'Corner Scale',
					'fxVScale' => 'Vertical Scale',
					'fxFall' => 'Fall',
					'fxFPulse' => 'Forward Pulse',
					'fxRPulse' => 'Rotate Pulse',
					'fxHearbeat' => 'Heartbeat',
					'fxCoverflow' => 'Cover Flow',
					'fxRotateSoftly' => 'Rotate Me Softly',
					'fxDeal' => 'Deal Em',
					'fxFerris' => 'Ferris Wheel',
					'fxShinkansen' => 'Shinkansen',
					'fxSnake' => 'Snake',
					'fxShuffle' => 'Shuffle',
					'fxPhotoBrowse' => 'Photo Browse',
					'fxSlideBehind' => 'Slide Behind',
					'fxVacuum' => 'Vacuum',
					'fxHurl' => 'Hurl It',
				),
				'default_value' => 'fxCorner',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5398a4e7ad392',
				'label' => 'Blog Page',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5398a5158689f',
				'label' => 'Select Style',
				'name' => 'nill_blogselectstyle',
				'type' => 'select',
				'instructions' => 'Select Page Style: Categories, Archive, Tags, Search Page',
				'choices' => array (
					'list' => 'List Blog',
					'listgrid' => 'List Grid Blog',
					'grid' => 'Grid Blog',
					'read' => 'Read Blog',
				),
				'default_value' => 'list',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5398a540868a0',
				'label' => 'Select Layouts',
				'name' => 'nill_blogselectlay',
				'type' => 'select',
				'instructions' => 'Select Page Layouts: Categories, Archive, Tags, Search Page',
				'choices' => array (
					'full' => 'Fullwidth',
					'right' => 'Right Sidebar',
					'left' => 'Left Sidebar',
				),
				'default_value' => 'full',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5393601076692',
				'label' => 'Footer',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5393601976693',
				'label' => 'Newsletter',
				'name' => 'nill_footnewsletter',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Newslette Widget in Footer',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5393609dcaed1',
				'label' => 'Footer Bar',
				'name' => 'nill_footerbar',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Footer Bar',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539360ef7f106',
				'label' => 'Register Text',
				'name' => 'nill_footerregistertext',
				'type' => 'text',
				'instructions' => 'Sample: Copright 2014 / Nilltheme.net',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393609dcaed1',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Text:',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539361938ac0f',
				'label' => 'Footer Social Icons',
				'name' => 'nill_footericons',
				'type' => 'repeater',
				'instructions' => 'Add Footer Social Icons',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393609dcaed1',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_539361b38ac10',
						'label' => 'Add Fa Icons',
						'name' => 'add_fa_icons',
						'type' => 'text',
						'instructions' => 'All Icon is here: http://fortawesome.github.io/Font-Awesome/icons/ <br> Sample: fa-facebook',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Icon:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_539361ee8ac11',
						'label' => 'Add Icon Link',
						'name' => 'add_icon_link',
						'type' => 'text',
						'instructions' => 'Add Your Link',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Link:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Icons',
			),
			array (
				'key' => 'field_539c85edeea62',
				'label' => 'APP',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539c85f8eea63',
				'label' => 'Loading Percent',
				'name' => 'nill_appload',
				'type' => 'true_false',
				'instructions' => 'Display Show or Hide Ajax Loading Percent',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-page-blog-settings',
		'title' => 'Nill Page Blog Settings',
		'fields' => array (
			array (
				'key' => 'field_53959343348c3',
				'label' => 'Blog Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5395932f348c2',
				'label' => 'Select Blog Categories',
				'name' => 'nill_homeblogcat',
				'type' => 'taxonomy',
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53959354348c4',
				'label' => 'Show Post',
				'name' => 'nill_homeblogshows',
				'type' => 'number',
				'instructions' => 'Sample: 10',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Show Post:',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5398314a7fa2d',
				'label' => 'Blog Style',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539831527fa2e',
				'label' => 'Select Style',
				'name' => 'nill_selectblogstyle',
				'type' => 'select',
				'instructions' => 'Select Your Blog Style',
				'choices' => array (
					'list' => 'List Blog',
					'listgrid' => 'List Grid Blog',
					'grid' => 'Grid Blog',
					'read' => 'Read Blog',
				),
				'default_value' => 'list',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53983190c5851',
				'label' => 'Select Layouts',
				'name' => 'nill_selbloglayouts',
				'type' => 'select',
				'choices' => array (
					'full' => 'Fullwidth',
					'right' => 'Right Sidebar',
					'left' => 'Left Sidebar',
				),
				'default_value' => 'full',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-blog.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-page-contact-settings',
		'title' => 'Nill Page Contact Settings',
		'fields' => array (
			array (
				'key' => 'field_539ad620637f6',
				'label' => 'Google Map',
				'name' => 'nill_contactpagemap',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-page-filter-settings',
		'title' => 'Nill Page Filter Settings',
		'fields' => array (
			array (
				'key' => 'field_5399c47869269',
				'label' => 'Filter Categories',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5399c43f69267',
				'label' => 'Select Categories',
				'name' => 'nill_filtercat',
				'type' => 'taxonomy',
				'instructions' => 'Select Categories',
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5399c45f69268',
				'label' => 'Show Post',
				'name' => 'nill_filterableshows',
				'type' => 'number',
				'instructions' => 'Sample: 10',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Show Posts:',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5399c4866926a',
				'label' => 'Filter Layouts',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5399c3f4fff06',
				'label' => 'Select Grid',
				'name' => 'nill_filterselgrid',
				'type' => 'select',
				'instructions' => 'Select Layouts Grid',
				'choices' => array (
					3 => '4 Grid',
					4 => '3 Grid',
					6 => '2 Grid',
				),
				'default_value' => 3,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5399c4946926b',
				'label' => 'Add Filter',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5399c4afe2ada',
				'label' => 'Add Filter',
				'name' => 'nill_filterstab',
				'type' => 'repeater',
				'instructions' => 'Add Your Filter Buttons',
				'sub_fields' => array (
					array (
						'key' => 'field_5399c4cce2adb',
						'label' => 'Filter Name',
						'name' => 'nill_filtername',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Filter Name:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Filter',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-filter.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-page-home-settings',
		'title' => 'Nill Page Home Settings',
		'fields' => array (
			array (
				'key' => 'field_539adc6995aef',
				'label' => 'Home Page Builder',
				'name' => 'nill_modul_builder',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Slider',
						'name' => 'nill_moduleslider',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_539aebe099b2a',
								'label' => 'Select Effects',
								'name' => 'nill_modsliderefx',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'fxSoftScale' => 'Soft Slide',
									'fxPressAway' => 'Press Away',
									'fxSideSwing' => 'Side Swing',
									'fxFortuneWheel' => 'Fortune Wheel',
									'fxSwipe' => 'Swipe',
									'fxPushReveal' => 'Push Reveal',
									'fxSnapIn' => 'Snap In',
									'fxLetMeIn' => 'Let Me In',
									'fxStickIt' => 'Stick It',
									'fxArchiveMe' => 'Archive Me',
									'fxVGrowth' => 'Vertical Growth',
									'fxSlideBehind' => 'Slide Behind',
									'fxSoftPulse' => 'Soft Pulse',
									'fxEarthquake' => 'Earthquake',
									'fxCliffDiving' => 'Cliffdiving',
								),
								'default_value' => 'fxSoftScale',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_539af372698f3',
								'label' => 'Add Slide',
								'name' => 'nill_addslide',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_539af387698f4',
										'label' => 'Title',
										'name' => 'nill_slidertitle',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => 'Title:',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539af39e698f5',
										'label' => 'Link',
										'name' => 'nill_sliderlink',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => 'Link:',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
									array (
										'key' => 'field_539afc6fcd937',
										'label' => 'Select Icons',
										'name' => 'nill_slidericons',
										'type' => 'select',
										'column_width' => '',
										'choices' => array (
											'fa-file' => 'Normal Post',
											'fa-music' => 'Music Post',
											'fa-video-camera' => 'Video Post',
											'fa-picture-o' => 'Picture Post',
											'fa-camera' => 'Gallery Post',
											'fa-map-marker' => 'Event Post',
											'fa-quote-left' => 'Quote Post',
											'fa-link' => 'Link Post',
										),
										'default_value' => 'fa-file',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_539af3b1698f6',
										'label' => 'Image',
										'name' => 'nill_sliderimage',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'nill-thumbsmall',
										'library' => 'all',
									),
									array (
										'key' => 'field_539af5c9d0afd',
										'label' => 'If is Current Slide?',
										'name' => 'nill_currentslide',
										'type' => 'true_false',
										'column_width' => '',
										'message' => '',
										'default_value' => 0,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Slide',
							),
						),
					),
					array (
						'label' => 'News',
						'name' => 'nill_modulenews',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_539b38828e173',
								'label' => 'Title',
								'name' => 'nill_modtitlenews',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Title:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539b38b19b49c',
								'label' => 'Title Two',
								'name' => 'nill_modtitletwonews',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Title Two:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539b38302fe72',
								'label' => 'Select Style',
								'name' => 'nill_modselectnews',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'list' => 'List Style',
									'listgrid' => 'Cube Style',
									'grid' => 'Grid Style',
									'event' => 'Event Style',
								),
								'default_value' => 'list',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_539b55f386cd6',
								'label' => 'Background is Grey?',
								'name' => 'nill_modulebacknews',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_539b37e82fe70',
								'label' => 'Select Categories',
								'name' => 'nill_modselectcatnews',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'checkbox',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_539b38062fe71',
								'label' => 'Show Post',
								'name' => 'nill_modshowsnews',
								'type' => 'number',
								'instructions' => 'Sample: 3',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Show Posts:',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array (
								'key' => 'field_539b56e28d73a',
								'label' => 'Add Button',
								'name' => 'nill_modulebtnnews',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
							array (
								'key' => 'field_539b56f68d73b',
								'label' => 'Button Title',
								'name' => 'nill_modulebtntitle',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_539b56e28d73a',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Title:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539b570e8d73c',
								'label' => 'Button Link',
								'name' => 'nill_modulebtnlink',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_539b56e28d73a',
											'operator' => '==',
											'value' => '1',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Link:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Mixed Photo',
						'name' => 'nill_modulemixed',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_539b78cdf321c',
								'label' => 'Title',
								'name' => 'nill_modtitlemix',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Title:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539b78e5f321d',
								'label' => 'Title Two',
								'name' => 'nill_modtitlemixtwo',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => 'Title Two:',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539b75327de03',
								'label' => 'Select Categories',
								'name' => 'nill_modmixcat',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'checkbox',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_539b754c7de04',
								'label' => 'Show Picture',
								'name' => 'nill_modmixshow',
								'type' => 'number',
								'instructions' => 'Sample: 10',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
					),
				),
				'button_label' => 'Add Modules',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/page-builder.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'featured_image',
				8 => 'categories',
				9 => 'tags',
				10 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-page-settings',
		'title' => 'Nill Page Settings',
		'fields' => array (
			array (
				'key' => 'field_539ad47bb9d85',
				'label' => 'Slider',
				'name' => 'nill_albumsinpicslider',
				'type' => 'gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-link-settings',
		'title' => 'Nill Post Link Settings',
		'fields' => array (
			array (
				'key' => 'field_53957ad4fdb1a',
				'label' => 'Link',
				'name' => 'nill_postlink',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Link:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'link',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-quote-settings',
		'title' => 'Nill Post Quote Settings',
		'fields' => array (
			array (
				'key' => 'field_539576a36a028',
				'label' => 'Quote Text',
				'name' => 'nill_quotetext',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539576b96a029',
				'label' => 'Quote Says',
				'name' => 'nill_quotesays',
				'type' => 'text',
				'instructions' => 'Sample: John Doe',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Says:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'quote',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_theme-style-settings',
		'title' => 'Theme Style Settings',
		'fields' => array (
			array (
				'key' => 'field_539dc2cfd15f6',
				'label' => 'Font Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539dc2dad15f7',
				'label' => 'Import Paragraph Font',
				'name' => 'nill_styleimportfone',
				'type' => 'text',
				'instructions' => 'Add Google Web Font
	<br>
	Sample: @import url(http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900,200,100);',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Font:',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539dc34708f25',
				'label' => 'Paragraph Font Family',
				'name' => 'nill_styleimportfonefam',
				'type' => 'text',
				'instructions' => 'Add Font Family
	<br>
	Sample: font-family: \'Raleway\', sans-serif;',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Font Family:',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539dc5468f820',
				'label' => 'Import H1, H2, H3, H4, H5, H6 Font',
				'name' => 'nill_styleimportftwo',
				'type' => 'text',
				'instructions' => 'Add Google Web Font
	<br>
	Sample: @import url(http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900,200,100);',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Font:',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539dc5638f821',
				'label' => 'H1, H2, H3, H4, H5, H6 Font Font Family',
				'name' => 'nill_styleimportftwofam',
				'type' => 'text',
				'instructions' => 'Add Font Family
	<br>
	Sample: font-family: \'Raleway\', sans-serif;',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Font Family:',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539dc6167f58c',
				'label' => 'Theme Color',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539dc6227f58d',
				'label' => 'Background Color',
				'name' => 'nill_colorone',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc6f4c7449',
				'label' => 'Main Color',
				'name' => 'nill_colortwo',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc7769f73a',
				'label' => 'Main Color Hover',
				'name' => 'nill_colorthree',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc8163895e',
				'label' => 'P Font Color',
				'name' => 'nill_colorfour',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc89396d8e',
				'label' => 'H1, H2, H3 Font Color',
				'name' => 'nill_colorfive',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc8c8f5407',
				'label' => 'H4, H5, H6 Font Color',
				'name' => 'nill_colorsix',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc95188070',
				'label' => 'Dark Font Color',
				'name' => 'nill_colorseven',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc9ab5b8b7',
				'label' => 'White Font Color',
				'name' => 'nill_coloreight',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dc9f4127fa',
				'label' => 'Grey Font Color',
				'name' => 'nill_colornine',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dca9a73993',
				'label' => 'Background Light One',
				'name' => 'nill_colorten',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dcaddf36f8',
				'label' => 'Background Light Two',
				'name' => 'nill_coloreleven',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dcb83de832',
				'label' => 'Background Dark One',
				'name' => 'nill_colordone',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dcbca7b9ee',
				'label' => 'Background Dark Two',
				'name' => 'nill_colordtwo',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
			array (
				'key' => 'field_539dcbf3531ce',
				'label' => 'Background Dark Three',
				'name' => 'nill_colordthree',
				'type' => 'color_picker',
				'instructions' => 'Select Color',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-theme-style',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-album-settings',
		'title' => 'Nill Post Album Settings',
		'fields' => array (
			array (
				'key' => 'field_538ec0ceaeb60',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538ebfd00991b',
				'label' => 'Label Name',
				'name' => 'nill_singername',
				'type' => 'text',
				'instructions' => 'Add Singer Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Singer Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538ec13170707',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53936c89c3737',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hidepostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539385b93e9c5',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hideposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53936d412713b',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hiderelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538ec0fc1a27b',
				'label' => 'Add Track',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5390bace0d16b',
				'label' => 'Select Style',
				'name' => 'nill_audiostyle',
				'type' => 'select',
				'instructions' => 'Select Audio Style',
				'choices' => array (
					'none' => 'None',
					'track' => 'Track Playlist',
					'soundcloud' => 'Soundcloud',
					'custom' => 'Custom Iframe',
				),
				'default_value' => 'none',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539072bc6ccea',
				'label' => 'Add Audio Track',
				'name' => 'nill_postaudio',
				'type' => 'repeater',
				'instructions' => 'Add Audio Track',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5390bace0d16b',
							'operator' => '==',
							'value' => 'track',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_539072f115740',
						'label' => 'Select Track Channell',
						'name' => 'nill_selecttrack',
						'type' => 'select',
						'required' => 1,
						'column_width' => '',
						'choices' => array (
							'upload' => 'Upload Mp3',
							'link' => 'Link Mp3',
						),
						'default_value' => 'upload',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_5390738c97bfc',
						'label' => 'Track Title',
						'name' => 'nill_uploadtracktitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_539089caf9cf0',
						'label' => 'Track Link',
						'name' => 'nill_uploadtracklink',
						'type' => 'text',
						'required' => 1,
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_539072f115740',
									'operator' => '==',
									'value' => 'link',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Link:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5390733c97bfb',
						'label' => 'Upload Mp3',
						'name' => 'nill_uploadmp',
						'type' => 'file',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_539072f115740',
									'operator' => '==',
									'value' => 'upload',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_53908bf64b155',
						'label' => 'Downloadable',
						'name' => 'nill_trackdwonload',
						'type' => 'true_false',
						'instructions' => 'Downloadable?',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_5390a3a04eea9',
						'label' => 'Buy Now',
						'name' => 'nill_trackbuynow',
						'type' => 'true_false',
						'instructions' => 'If open Buy Now?',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_5390a3c14eeaa',
						'label' => 'Price',
						'name' => 'nill_trackprice',
						'type' => 'text',
						'instructions' => 'Sample: $3.99',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a3a04eea9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Price:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5390a3eb4eeab',
						'label' => 'Buy Link',
						'name' => 'nill_trackpricelink',
						'type' => 'text',
						'instructions' => 'Buy Link',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a3a04eea9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Link:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5390a66f2b7c8',
						'label' => 'Add Video',
						'name' => 'nill_trackaddvideo',
						'type' => 'true_false',
						'instructions' => 'If add video?',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_5390a6892b7c9',
						'label' => 'Select Video Channell',
						'name' => 'nill_trackvideochannell',
						'type' => 'select',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'upload' => 'Upload',
							'youtube' => 'Youtube',
							'vimeo' => 'Vimeo',
							'custom' => 'Custom Iframe',
						),
						'default_value' => 'upload',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_5390a6fda764f',
						'label' => 'Upload Video (Mp4)',
						'name' => 'nill_trackyouruploadvid',
						'type' => 'file',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a6892b7c9',
									'operator' => '==',
									'value' => 'upload',
								),
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_53916432f0a64',
						'label' => 'Upload Video (Ogg)',
						'name' => 'nill_trackyouruploadogg',
						'type' => 'file',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a6892b7c9',
									'operator' => '==',
									'value' => 'upload',
								),
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_5390abd21f06f',
						'label' => 'Youtube',
						'name' => 'nill_youtube',
						'type' => 'text',
						'instructions' => 'Sample Link: http://www.youtube.com/watch?v=keDneypw3HY <br> Note: Only Add: keDneypw3HY ',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a6892b7c9',
									'operator' => '==',
									'value' => 'youtube',
								),
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'http://www.youtube.com/watch?v=',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5390ae1b5de14',
						'label' => 'Vimeo',
						'name' => 'nill_vimeo',
						'type' => 'text',
						'instructions' => 'Sample Link: https://vimeo.com/23534361 <br> Note: Only Add: 23534361',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a6892b7c9',
									'operator' => '==',
									'value' => 'vimeo',
								),
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'https://vimeo.com/',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5390b4011160b',
						'label' => 'Custom Iframe',
						'name' => 'nill_custom',
						'type' => 'textarea',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390a6892b7c9',
									'operator' => '==',
									'value' => 'custom',
								),
								array (
									'field' => 'field_5390a66f2b7c8',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'html',
					),
					array (
						'key' => 'field_5390b6315b179',
						'label' => 'Add Lyrics',
						'name' => 'nill_addlyrics',
						'type' => 'true_false',
						'instructions' => 'If add lyrics?',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_5390b6485b17a',
						'label' => 'Add Lyrics',
						'name' => 'nill_tracklyrics',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_5390b6315b179',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Track',
			),
			array (
				'key' => 'field_5390bcc0e9e70',
				'label' => 'Add Soundcloud',
				'name' => 'nill_addsoundcloud',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5390bace0d16b',
							'operator' => '==',
							'value' => 'soundcloud',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_5390bd6096d35',
				'label' => 'Add Custom Iframe',
				'name' => 'nill_addcustomframe',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5390bace0d16b',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539168523451e',
				'label' => 'Buttons',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5391685c3451f',
				'label' => 'Button One',
				'name' => 'nill_trackbtnone',
				'type' => 'true_false',
				'instructions' => 'Open Button One?',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5391689bc6fe1',
				'label' => 'Button Name',
				'name' => 'nill_trackonebtnname',
				'type' => 'text',
				'instructions' => 'Button Name',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5391685c3451f',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Button Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539168b8c6fe2',
				'label' => 'Button Link',
				'name' => 'nill_trackonebtnlink',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5391685c3451f',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Button Link:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5391688234520',
				'label' => 'Button Two',
				'name' => 'nill_trackbtntwo',
				'type' => 'true_false',
				'instructions' => 'Open Button Two?',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539169fffae81',
				'label' => 'Button Name',
				'name' => 'nill_tracktwobtnname',
				'type' => 'text',
				'instructions' => 'Button Name',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5391688234520',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Button Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53916a17fae82',
				'label' => 'Button Link',
				'name' => 'nill_tracktwobtnlink',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5391688234520',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Button Link:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5391b529b7a3c',
				'label' => 'Slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5391b532b7a3d',
				'label' => 'Picture Slider',
				'name' => 'nill_albumpicslider',
				'type' => 'gallery',
				'instructions' => 'Add Album Slider Gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
			array (
				'key' => 'field_5391baebcc435',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5391bbc24e699',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-event-settings',
		'title' => 'Nill Post Event Settings',
		'fields' => array (
			array (
				'key' => 'field_53944069de5d9',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944069deda6',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53944069e0682',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hideevpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944069e1659',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hideeveposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944069e0ef3',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hideevrelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944069e1d7e',
				'label' => 'Add Event',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539441f0eee36',
				'label' => 'Countdown Time',
				'name' => 'nill_eventtime',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_539441dceee35',
				'label' => 'Google Map',
				'name' => 'nill_map',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_53944069df515',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944069dfd00',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'aside',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-gallery-settings',
		'title' => 'Nill Post Gallery Settings',
		'fields' => array (
			array (
				'key' => 'field_53944a4f14959',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944a4f1e30e',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53944a4f7d330',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hidegalpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944a4f7e29f',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hidegalposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944a4f7db29',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hidegalrelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53944a4f59867',
				'label' => 'Slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944aab3accd',
				'label' => 'Picture Slider',
				'name' => 'nill_albumgalpicslider',
				'type' => 'gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
			array (
				'key' => 'field_53944a6fb1137',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944a7bb1138',
				'label' => 'Add Gallery',
				'name' => 'nill_postgallery',
				'type' => 'gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
			array (
				'key' => 'field_53944a4f698d4',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53944a4f78f49',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-image-settings',
		'title' => 'Nill Post Image Settings',
		'fields' => array (
			array (
				'key' => 'field_539458baa0853',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539458baa0f44',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539458baa2b07',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hideimpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539458baa37fa',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hideimposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539458baa3143',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hideimrelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539458baa1684',
				'label' => 'Slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539458baa4c74',
				'label' => 'Picture Slider',
				'name' => 'nill_albumimpicslider',
				'type' => 'gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
			array (
				'key' => 'field_539458baa1cb5',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539458baa22dc',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'image',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-image-settings-2',
		'title' => 'Nill Post Image Settings',
		'fields' => array (
			array (
				'key' => 'field_5395820fe76d5',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5395820fe7eb4',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5395820fe9bb4',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hideimpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5395820fea9b8',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hideimposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5395820fea2fd',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hideimrelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'quote',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'link',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-settings',
		'title' => 'Nill Post Settings',
		'fields' => array (
			array (
				'key' => 'field_53957f4342f6a',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53957f43459d0',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53957f434c5c5',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hidesinpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53957f434d439',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hidesinposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53957f434ccdf',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hidesinglerel',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53957f43460a0',
				'label' => 'Slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53957f434daf4',
				'label' => 'Picture Slider',
				'name' => 'nill_albumsinpicslider',
				'type' => 'gallery',
				'preview_size' => 'nill-thumbsmall',
				'library' => 'all',
			),
			array (
				'key' => 'field_53957f4348614',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53957f4348e22',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'standard',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_nill-post-video-settings',
		'title' => 'Nill Post Video Settings',
		'fields' => array (
			array (
				'key' => 'field_539387929557c',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539387929636b',
				'label' => 'Filter Name',
				'name' => 'nill_filtername',
				'type' => 'text',
				'instructions' => 'Add Filter Name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Filter Name:',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539387929e087',
				'label' => 'Hide Post Detail',
				'name' => 'nill_hidevidpostdetail',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Detail',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539387929f0fb',
				'label' => 'Hide Post Tags',
				'name' => 'nill_hidevideposttags',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Post Tags Area',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539387929e966',
				'label' => 'Hide Related Posts',
				'name' => 'nill_hidevidrelatedposts',
				'type' => 'true_false',
				'instructions' => 'Show or Hide Related Posts',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_539389f7107c0',
				'label' => 'Add Video',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5393928b807e8',
				'label' => 'Select Channell',
				'name' => 'nill_postvidselchannell',
				'type' => 'select',
				'choices' => array (
					'upload' => 'Upload Video',
					'youtube' => 'Youtube',
					'vimeo' => 'Vimeo',
					'custom' => 'Custom Iframe',
				),
				'default_value' => 'upload',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_539392db9ee98',
				'label' => 'Upload Video (Mp4)',
				'name' => 'nill_trackyouruploadvid',
				'type' => 'file',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393928b807e8',
							'operator' => '==',
							'value' => 'upload',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5393931b55ec0',
				'label' => 'Upload Video (Ogg)',
				'name' => 'nill_trackyouruploadogg',
				'type' => 'file',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393928b807e8',
							'operator' => '==',
							'value' => 'upload',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_539393bdfe14b',
				'label' => 'Youtube',
				'name' => 'nill_youtube',
				'type' => 'text',
				'instructions' => 'Sample Link: http://www.youtube.com/watch?v=keDneypw3HY <br> Note: Only Add: keDneypw3HY ',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393928b807e8',
							'operator' => '==',
							'value' => 'youtube',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://www.youtube.com/watch?v=',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539393ebfe14c',
				'label' => 'Vimeo',
				'name' => 'nill_vimeo',
				'type' => 'text',
				'instructions' => 'Sample Link: https://vimeo.com/23534361 <br> Note: Only Add: 23534361',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393928b807e8',
							'operator' => '==',
							'value' => 'vimeo',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://vimeo.com/',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53939456f7017',
				'label' => 'Custom Iframe',
				'name' => 'nill_custom',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5393928b807e8',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_539387929d14e',
				'label' => 'Reviews',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_539387929d83b',
				'label' => 'Album Reviews',
				'name' => 'nill_albumreviews',
				'type' => 'repeater',
				'instructions' => 'Add Your Reviews',
				'sub_fields' => array (
					array (
						'key' => 'field_5391bbf14e69a',
						'label' => 'Point Title',
						'name' => 'nill_postpointtitle',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Title:',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5391bc094e69b',
						'label' => 'Point Number',
						'name' => 'nill_postpointnumber',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'Number:',
						'append' => '',
						'min' => '',
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Points',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}


?>